config/routes.rb
WordApp2::Application.routes.draw do
  resources :words
  root 'words#index'

end

app/models/word.rb
class Word < ActiveRecord::Base
  before_save { self.word = word.downcase }
  validates :word, presence: true, length: { maximum: 50 },
                   uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to @word
    else
      render 'new'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    redirect_to words_path
  end

  private

  def word_params
    params.require(:word).permit(:word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WordApp2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_ messages.html.erb
<% if @word.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@word.errors.count, "error") %>.
    </div>
    <ul>
    <% @word.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @word.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@word.errors.count, "error") %>.
    </div>
    <ul>
    <% @word.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<% provide(:title, 'Add word') %>
<h1>Add word</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@word) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :word %>
      <%= f.text_field :word %>

      <%= f.submit "Add word", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<% provide(:title, @word.word) %>
<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<%= link_to 'Back', words_path %>